"""courseDesc table

Revision ID: 38e961169a86
Revises: 72783973e7d5
Create Date: 2023-06-14 10:13:28.748624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38e961169a86'
down_revision = '72783973e7d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_desc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coursename', sa.String(length=64), nullable=True),
    sa.Column('body', sa.String(length=1000), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('course_desc', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_desc_coursename'), ['coursename'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_desc', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_desc_coursename'))

    op.drop_table('course_desc')
    # ### end Alembic commands ###
